### ISSUE TITLE
[개선] Provisioning Volume Validation Check and List Management

### ISSUE THREAD

**Issue by hcloudclassic** [hcloud-classic/hcc-cello#2]
## 문제 상황

서버 생성시 프로비저닝될 OS의 list에 없는 OS로 생성시 OS 볼륨 생성은 실패 하지만, 이와는 별개로 DATA 볼륨은 그대로 생성 요청이됨.

## 개선

Violin에 서버 생성 로직에서는 OS 볼륨 혹은 DATA 볼륨 생성 실패시 롤백 할 수 있도록 구현 필요.

@hcloud-classic/innogrid

**Comment by niconicodex** [comment]
## 개선
  - 볼륨 생성 실패시 생성 요청 server uuid에 해당 하는 볼륨은 삭제하여 롤백
  - Config 및 iscsi설정 초기화
